name: pghw1
version: '3.9'
services:
  db:
    container_name: pgdb
    image: mirror.gcr.io/postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./logs:/var/log/postgresql
    networks:
      - pg
    ports:
      - 5000:5432

networks:
  pg:
    name: pg
